@startuml
skinparam linetype polyline
'skinparam linetype ortho
' ======== Abstract Classes and Enumerations ========
enum Difficulty {
Easy
Medium
Hard
}

Difficulty --* MathGamePage
Difficulty --* SudokuGamePage
Difficulty --* PairMatchingGamePage
Difficulty --* AimTrainerPage

enum Operation {
Addition
Substraction
Multiplication
Division
}

Operation --* MathGamePage


' ======== User/Account Domain ========
'abstract class User {
'+int userId
'+String username
'+String password
'+boolean isAuthorized
'+login()
'+logout()
'+signUp()
'}

'User <|-- Player

' ======== Application Pages ========
abstract class BlazerComponentBase {
}

class AccountPage extends BlazerComponentBase {
  - string username 
  + string accountUsername
  + string accountPassword
  + bool isUsernameNew
  + bool incorectLogIn

  + LogInEventAsync()
  + LogOffEvent()
  + SignUpEventAsync()
}

class User {
  + int Id
  + Username : string
  + Password : string
  + bool IsPrivate
  + List<Score<MathGamePageData>> MathGamePageScores
  + List<Score<SudokuData>> SudokuScores
  + List<Score<AimTrainerData>> AimTrainerScores
  + List<Score<PairUpData>> PairUpScores
}

User <.. AccountPage
UserController ..> User

class MathGamePage extends BlazerComponentBase {
-int score
-string question
-List<int> options
-boolean? isCorrect
+generateQuestion()
+checkAnswer(int option)
}

class SudokuGamePage extends BlazerComponentBase {
-int[,] grid
-int[,] solution
-int elapsedTime
-List<int> possibleValues
+generateSudoku()
+checkSolution()
}

class PairMatchingGamePage extends BlazerComponentBase {
-List<Card> cards
-int matchedPairs
-int mistakes
+generateCardDeck()
+checkSelectedCards()
}

class AimTrainerPage extends BlazerComponentBase {
-int score
-int x,
-int y targetPosition
-int moveDirection
+onTargetClicked()
+moveTarget()
}


class SettingsPage extends BlazerComponentBase {
  - bool IsPrivateActive
  - TogglePrivate()
}

class UserScoreDto <T: Class> {
  + string Username
  + bool IsPrivate
  + DateTime Timestamp
  + T GameData 
  + ShowOtherDateTimeFormat()
}

UserScoreDto <.. StatisticsPage

MathGamePage ..> UserScoreDto
SudokuGamePage ..> UserScoreDto
PairMatchingGamePage ..> UserScoreDto
AimTrainerPage ..> UserScoreDto


 UserScoreDto <.. MathGamePageController
 UserScoreDto <.. SudokuController
 UserScoreDto <.. PairUpController  
 UserScoreDto <.. AimTrainerController



' ======== Statistics/High Score Domain ========
class StatisticsPage extends BlazerComponentBase {
  + Dictionary<string, List<UserScoreDto>> GameScores 
  + Dictionary<string, int> GamePlayedCounts
  + Dictionary<string, GameScore> GameHighscores
  + Dictionary<string, GameScore> GameAllTimeAverages
  + Dictionary<string, List<AverageScoreDto>> GameAverageLast7Days

  - ToggleGameInfo()
  - SetActiveDifficulty()
  - SetActiveSizeSudoku()
  + LoadAllGameScoresAsync()
  + LoadGameScoresAsync()
  + LoadAllGameDatasetsAsync()
  + LoadGameDatasetsAsync()
}



class AverageScoreDto {
  + Date : DateTime
  + Score : GameScore
}

AverageScoreDto <.. StatisticsPage
AverageScoreDto <.. AccountScoreController
AccountScoreController ..> UserScoreDto


' ======== Timer Service ========
class TimerService {
+int RemainingTime
+Start()
+Stop()
+OnTick()
}

AimTrainerPage *-- TimerService
SudokuGamePage *-- TimerService
PairMatchingGamePage *-- TimerService
MathGamePage *-- TimerService


' ======== Services (Subset) ========

'User ..> AuthService

' ======== Controllers ========
class AccountScoreController <<Controller>> {
+GetGameScores()
+GetGameHighscore()
+GetGameMatchesPlayed()
+GetGameAverageScore()
+GetGameAverageScoreLast7Days()
}


class AimTrainerController <<Controller>> {
+SaveScoreAsync()
+GetUserHighscoreAsync()
+GetTopScoresAsync()
}

class MathGamePageController <<Controller>> {
+GetQuestion()
+GetOptions()
+CheckAnswer()
+SaveScoreAsync()
+GetUserHighscoreAsync()
+GetTopScoresAsync()
}

class PairUpController <<Controller>> {
+SaveScoreAsync()
+GetUserHighscoreAsync()
+GetTopScoresAsync()
}

class SudokuController <<Controller>> {
+GenerateSolvedSudoku()
+HideNumbers()
+SaveScoreAsync()
+GetUserHighscoreAsync()
+GetTopScoresAsync()
}

class UserController <<Controller>> {
+CreateUserAsync()
+LogInAsync()
+LogOff()
+GetUsernamesAsync()
+ChangePrivateAsync()
+GetPrivateAsync()
}



' ======== Relationships for Controllers ========
SettingsPage ..> User


class AccountScoreService {
  - int lastGamesCount
  - IScoreRepository repository

  + AccountScoreService()
  - Task<List<UserScoreDto<T>>> GetUserSpecificScores<T>()
  + Task<List<UserScoreDto<T>>> GetUserScores<T>()
  + Task<GameScore> GetHighscore<T>()
  + Task<GameScore> GetAllTimeAverageScore<T>()
  + Task<int> GetMatchesPlayed<T>()
  + Task<List<AverageScoreDto>> GetAverageScoreLast7Days<T>()
}

AccountScoreService *-- AccountScoreController
AccountScoreService ..> UserScoreDto

class AimTrainerService {
  - IScoreRepository _scoreRepository

  + AimTrainerService()
  + Task AddScoreToDbAsync()
  + Task<UserScoreDto<AimTrainerData>> GetUserHighscoreAsync()
  + Task<List<UserScoreDto<AimTrainerData>>> GetTopScoresAsync()
}

AimTrainerService *-- AimTrainerController
AimTrainerService ..> UserScoreDto

class PairUpService {
  - IScoreRepository _scoreRepository

  + PairUpService()
  + Task AddScoreToDbAsync()
  + Task<UserScoreDto<PairUpData>> GetUserHighscoreAsync()
  + Task<List<UserScoreDto<PairUpData>>> GetTopScoresAsync()
}

PairUpService *-- PairUpController
PairUpService ..> UserScoreDto

class SudokuService {
  - IntVar[,] _possibleGrid
  - SolutionCollector _solutionCollector

  + GetUserHighscoreAsync()
  + GetTopScoresAsync()
  + HideNumbers()
  + GenerateSolvedSudoku()
  - SolveSudoku()
  - IsValidMove()
}

SudokuService *-- SudokuController
SudokuService ..> UserScoreDto

class UserService {
  - UserTrackingService _userTrackingService

  + UserService()
  + CreateUserAsync()
  + LogInToUserAsync()
  + LogOffFromUser()
  + GetUsernamesAsync()
  + ChangePrivateAsync()
  + GetPrivateAsync()
}

UserService *-- UserController

class UserTrackingService {
  - ConcurrentDictionary<string, DateTime> _activeUsers

  + AddOrUpdateUser()
  + RemoveUser()
  + GetActiveUsers()
}

UserTrackingService *-- UserService

class MathGameService {
  - IMathCalculationService _mathCalculationService
  - IMathGenerationService _mathGenerationService
  + int Answer
  + List<int> numbers
  + List<Operation> operations

  + MathGameService()
  + GenerateQuestion()
  + CheckAnswer()
  + GenerateOptions()
  - BuildQuestionToString()
}

MathGameService *-- MathGamePageController

class ScoreRepository {
  - UserDbContext _userDbContext

  + ScoreRepository()
  + AddScoreToUserAsync()
  + GetHighscoreFromUserAsync()
  + GetAllScoresAsync()
}

ScoreRepository *-- AccountScoreService

class UserRepository {
  - UserDbContext _userDbContext

  + UserRepository()
  + Task CreateUserAsync()
  + Task<List<User>> GetAllUsersAsync()
  + Task<bool> ValidateUserAsync()
  + Task ChangePrivateAsync()
  + Task<bool> GetPrivateAsync()
}

@enduml